### ISSUE TITLE
log4j

### ISSUE THREAD

**Issue by mkunzecw** [git-as-svn/git-as-svn#471]
The debian releases contain vulnerable log4j version

https://github.com/slonopotamus/git-as-svn/blob/4b8cdcc4c4472101378ea35e593f029a41e87831/build.gradle.kts#L103

**Comment by slonopotamus** [comment]
Are you aware of any log4j version that is not vulnerable?

2.17.0 is also broken: https://www.bleepingcomputer.com/news/security/log4j-2171-out-now-fixes-new-remote-code-execution-bug/

**Comment by slonopotamus** [comment]
Possibly the proper fix is to get rid of log4j completely.

**Comment by slonopotamus** [comment]
git-as-svn 2.0.0 was just released. It includes log4j 2.17.1.

**Comment by mkunzecw** [comment]
agree, but thanks for the fix!
